# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Dependent_Window_Deduction.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 165)
        Form.setStyleSheet("background-color: rgb(103, 103, 103);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 21))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 16pt \"Calibri\";")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 171, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 201, 21))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 italic 16pt \"Calibri\";")
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(210, 50, 141, 21))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 130, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 130, 75, 23))
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 221, 21))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Введите сумму:"))
        self.label_2.setText(_translate("Form", "Категория списания:"))
        self.comboBox.setItemText(0, _translate("Form", "Погашения кредита"))
        self.comboBox.setItemText(1, _translate("Form", "Оплата за проезд"))
        self.comboBox.setItemText(2, _translate("Form", "Покупка товара"))
        self.comboBox.setItemText(3, _translate("Form", "Оплата налогов"))
        self.pushButton.setText(_translate("Form", "ОK"))
        self.pushButton_2.setText(_translate("Form", "Отмена"))
        self.label_3.setText(_translate("Form", "Введите сумму корректно"))
